### PR TITLE
Fix filename check

### PR DESCRIPTION
**Pull request by rb83421**
The sanitize_filename function was causing crashes for me here is my fix.

What is the intention to merge back to pe-st repo to master?

### CODE REVIEW

**Comment by rb83421** [comment]
I'm not sure why the activity name first needs to processed to an unicode with:
` cleaned_filename = unicodedata.normalize('NFKD', name).encode('ASCII', 'ignore') if name else ''`
just check if it contain forbidden chars and remove then (that is my though with this fix)

**Comment by telemaxx** [comment]
> What is the intention to merge back to pe-st repo to master?

?? not understanding this.
Default branch from pe-st is developer.

I use my "Python3" branch and send pr to feature/p3

**Comment by telemaxx** [comment]
> 
> 
> I'm not sure why the activity name first needs to processed to an unicode with:
> ` cleaned_filename = unicodedata.normalize('NFKD', name).encode('ASCII', 'ignore') if name else ''`
> just check if it contain forbidden chars and remove then (that is my though with this fix)

the most things are not done by me. i just start the Python 3 porting.
Many things i did not understand, i am just a hobby programmer.

A soon Peter solved the remaining bugs with python3, i think he will merge p3 branch into his default branch.

**Comment by rb83421** [comment]
This fix is obsolete in the new Python3 branch it is solved (in an other way)

**Pull request closed without merging**
