### PR TITLE
Add new option

### PR DESCRIPTION
**Pull request by rb83421**
Added the new option again (that was implemented by ch8961). Also the 'all' option was not working with python3 yet.

Could you also test if these changes are working for you (hard to debug constantly to many request and wait for an hour)

### CODE REVIEW

**Comment by rb83421** [comment]
What i also noticed that the activities.csv contains byte array like b'23189' i.s.o. just string "23189"
Not sure if this i wrong, i don't use the csv, also i could not find an easy fix yet.

**Comment by telemaxx** [comment]
i did not recognized you're PRs... now i have set the watcher, to get informed when PRs arriving.  i will try to merge this evening.

**Comment by telemaxx** [comment]
i have just merged feature/p3 from pe-st to my Python3 branch.
Now i see some conflicts...
Could you resolve that conflicts and send new PRs?

**Comment by rb83421** [comment]
Conflicts for these branch are fixed

**Comment by rb83421** [comment]
I'm not the most experienced git user :). 
Should i have created an pull request directly toward ps-et p3 branch?

**Comment by telemaxx** [comment]
i think that would be the best. the pe-st fork seems to be the mother of all gcexport forks...

**Comment by telemaxx** [comment]
i am also not git master ;-) can only do some simple operations

**Comment by rb83421** [comment]
oke I close it here is opened a new on the p3 branch of pe-st

**Pull request closed without merging**
